# Generated by Django 2.2.7 on 2019-11-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, max_length=140, verbose_name='Activity')),
                ('prompt_time', models.IntegerField(default=0, verbose_name='Stop')),
            ],
            options={
                'ordering': ['prompt_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('question', 'Question'), ('email', 'Get email'), ('twitter', 'Twitter share')], max_length=20, verbose_name='Type name')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Video Title')),
                ('yt_video_id', models.CharField(max_length=50, verbose_name='Video Id')),
                ('email', models.EmailField(max_length=254, verbose_name='User')),
                ('duration', models.IntegerField(default=0, verbose_name='Video Duration')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(blank=True, max_length=140, verbose_name='Option')),
                ('action', models.CharField(choices=[('continue', 'Continue Video'), ('change_video', 'Change Video'), ('jump_to', 'Jump to Time')], max_length=20, verbose_name='Action')),
                ('jump_to_video', models.CharField(max_length=50, verbose_name='Video Id')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='video.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_email', models.EmailField(max_length=254, null=True, verbose_name='Viewer E-mail')),
                ('viewer_tweet', models.CharField(max_length=140, null=True, verbose_name='Viewer Tweet')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='video.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='video.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_types', to='video.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='video.Video'),
        ),
    ]
