# Generated by Django 2.2.7 on 2019-11-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20191120_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='jump_to_time',
            field=models.IntegerField(default=0, verbose_name='Video time'),
        ),
    ]
