# Generated by Django 2.2.7 on 2019-11-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Video Duration'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video Title'),
        ),
    ]
