# Generated by Django 2.2.7 on 2019-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20191120_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='question_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('question', 'Question'), ('email', 'Get email'), ('twitter', 'Twitter share')], default='question', max_length=20, verbose_name='Type name'),
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
