# Generated by Django 2.2.7 on 2019-11-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20191120_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='question_text',
            new_name='activity_text',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='question',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='activity',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='video.Video'),
        ),
    ]
