export const LOGIN = 'USER_LOGIN';
export const LOGOUT = 'USER_LOGOUT';

export const VIDEO_CREATE = 'VIDEO_CREATE';
export const VIDEO_RETRIEVE = 'VIDEO_RETRIEVE';
export const VIDEO_UPDATE = 'VIDEO_UPDATE';
export const VIDEO_DELETE = 'VIDEO_DELETE';

export const QUESTION_CREATE = 'QUESTION_CREATE';
export const QUESTION_RETRIEVE = 'QUESTION_RETRIEVE';
export const QUESTION_UPDATE = 'QUESTION_UPDATE';
export const QUESTION_DELETE = 'QUESTION_DELETE';

export const OPTION_CREATE = 'OPTION_CREATE';
export const OPTION_RETRIEVE = 'OPTION_RETRIEVE';
export const OPTION_UPDATE = 'OPTION_UPDATE';
export const OPTION_DELETE = 'OPTION_DELETE';

export const ANSWER_CREATE = 'ANSWER_CREATE';
export const ANSWER_RETRIEVE = 'ANSWER_RETRIEVE';
export const ANSWER_UPDATE = 'ANSWER_UPDATE';
export const ANSWER_DELETE = 'ANSWER_DELETE';
